const year_2021 = [
  "ANI 230",
  "ANI 231",
  "GAM 180",
  "GAM 181",
  "GAM 205",
  "GAM 226",
  "GAM 230",
  "GAM 240",
  "GAM 244",
  "GAM 245",
  "GAM 250",
  "GAM 312",
  "GAM 340",
  "GAM 341",
  "GAM 355",
  "GAM 365",
  "GAM 392",
  "GAM 394",
  "GAM 395",
  "GD 105",
  "IT 223"
];

const year_1920 = [
  "<span>GAM 226</span> Fundamentals of Game Design ",
  "<span>GAM 240</span> Playgramming ",
  "<span>GAM 244</span> Game Development I ",
  "<span>GD 105</span> Intro to Visual Design ",
  "<span>ANI 230</span> 3D Design and Modeling ",
  "<span>GAM 205</span> Games Literacy ",
  "<span>ANI 101</span> Animation for Non-Majors ",
  "<span>DC 201</span> Introduction to Screenwriting ",
  "<span>LSP 110</span> Discover Chicago ",
  "<span>LSP 111</span> Explore Chicago ",
  "<span>LSP 112</span> Focal Point Seminar ",
  "<span>WRD 103</span> Composition and Rhetoric I ",
  "<span>WRD 104</span> Composition and Rhetoric II ",
  "<span>GAM 341</span> Introduction to Level Design ",
  "<span>GAM 245</span> Game Development II ",
  "<span>GAM 340</span> Practical Scripting for Games ",
  "<span>ANI 231</span> 3D Animation ",
  "<span>GAM 229</span> Presentation and Communication ",
  "<span>GAM 230</span> Intro to Game Production ",
  "<span>LSP 200</span> Seminar on Multiculturalism in the United States ",
  "<span>GAM 355</span> Solo Game Development Project ",
  "<span>GAM 365</span> Advanced Game Design ",
  "<span>GAM 312</span> Playtesting ",
  "<span>GAM 250</span> Game Sound Design I ",
  "<span>IT 223</span> Data Analysis ",
  "<span>DC 228</span> Ethics in Computer Games and Cinema ",
  "<span>IT 228</span> Ethics in Computer Games and Cinema ",
  "<span>GAM 392</span> Game Modification Workshop ",
  "<span>GAM 394</span> Game Development Project I ",
  "<span>GAM 395</span> Game Development Project II "
];

const year_1819 = [
  "<span>GAM 226</span> Fundamentals of Game Design ",
  "<span>GAM 240</span> Playgramming ",
  "<span>GAM 244</span> Game Development I ",
  "<span>GD 105</span> Intro to Visual Design ",
  "<span>ANI 230</span> 3D Design and Modeling ",
  "<span>GAM 205</span> Games Literacy ",
  "<span>ANI 101</span> Animation for Non-Majors ",
  "<span>DC 201</span> Introduction to Screenwriting ",
  "<span>LSP 110</span> Discover Chicago ",
  "<span>LSP 111</span> Explore Chicago ",
  "<span>LSP 112</span> Focal Point Seminar ",
  "<span>WRD 103</span> Composition and Rhetoric I ",
  "<span>WRD 104</span> Composition and Rhetoric II ",
  "<span>GAM 341</span> Introduction to Level Design ",
  "<span>GAM 245</span> Game Development II ",
  "<span>GAM 340</span> Practical Scripting for Games ",
  "<span>ANI 231</span> 3D Animation ",
  "<span>GAM 229</span> Presentation and Communication ",
  "<span>GAM 230</span> Intro to Game Production ",
  "<span>LSP 200</span> Seminar on Multiculturalism in the United States ",
  "<span>GAM 355</span> Solo Game Development Project ",
  "<span>GAM 365</span> Advanced Game Design ",
  "<span>GAM 312</span> Playtesting ",
  "<span>GAM 250</span> Game Sound Design I ",
  "<span>IT 223</span> Data Analysis ",
  "<span>DC 228</span> Ethics in Computer Games and Cinema ",
  "<span>IT 228</span> Ethics in Computer Games and Cinema ",
  "<span>GAM 392</span> Game Modification Workshop ",
  "<span>GAM 394</span> Game Development Project I ",
  "<span>GAM 395</span> Game Development Project II "
];

const year_1718 = [
  "<span>GAM 226</span> Fundamentals of Game Design ",
  "<span>GAM 240</span> Playgramming ",
  "<span>GAM 244</span> Game Development I ",
  "<span>GD 105</span> Intro to Visual Design ",
  "<span>ANI 230</span> 3D Design and Modeling ",
  "<span>GAM 205</span> Games Literacy ",
  "<span>ANI 101</span> Animation for Non-Majors ",
  "<span>DC 201</span> Introduction to Screenwriting ",
  "<span>LSP 110</span> Discover Chicago ",
  "<span>LSP 111</span> Explore Chicago ",
  "<span>LSP 112</span> Focal Point Seminar ",
  "<span>WRD 103</span> Composition and Rhetoric I ",
  "<span>WRD 104</span> Composition and Rhetoric II ",
  "<span>GAM 341</span> Introduction to Level Design ",
  "<span>GAM 245</span> Game Development II ",
  "<span>GAM 340</span> Practical Scripting for Games ",
  "<span>ANI 231</span> 3D Animation ",
  "<span>GAM 229</span> Presentation and Communication ",
  "<span>GAM 230</span> Intro to Game Production ",
  "<span>LSP 200</span> Seminar on Multiculturalism in the United States ",
  "<span>GAM 355</span> Solo Game Development Project ",
  "<span>GAM 365</span> Advanced Game Design ",
  "<span>GAM 312</span> Playtesting ",
  "<span>GAM 250</span> Game Sound Design I ",
  "<span>IT 223</span> Data Analysis ",
  "<span>DC 228</span> Ethics in Computer Games and Cinema ",
  "<span>IT 228</span> Ethics in Computer Games and Cinema ",
  "<span>GAM 392</span> Game Modification Workshop ",
  "<span>GAM 394</span> Game Development Project I ",
  "<span>GAM 395</span> Game Development Project II "
];

const year_1617 = [
  "<span>GAM 226</span> Fundamentals of Game Design ",
  "<span>GAM 240</span> Playgramming ",
  "<span>GAM 244</span> Game Development I ",
  "<span>GD 105</span> Intro to Visual Design ",
  "<span>ANI 230</span> 3D Design and Modeling ",
  "<span>GAM 205</span> Evolution of Games ",
  "<span>ANI 101</span> Animation for Non-Majors ",
  "<span>DC 201</span> Introduction to Screenwriting ",
  "<span>LSP 110</span> Discover Chicago ",
  "<span>LSP 111</span> Explore Chicago ",
  "<span>LSP 112</span> Focal Point Seminar ",
  "<span>WRD 103</span> Composition and Rhetoric I ",
  "<span>WRD 104</span> Composition and Rhetoric II ",
  "<span>GAM 341</span> Introduction to Level Design ",
  "<span>GAM 245</span> Game Development II ",
  "<span>GAM 340</span> Practical Scripting for Games ",
  "<span>ANI 231</span> 3D Animation ",
  "<span>GAM 229</span> Presentation and Communication ",
  "<span>GAM 230</span> Intro to Game Production ",
  "<span>LSP 200</span> Seminar on Multiculturalism in the United States ",
  "<span>GAM 355</span> Solo Game Development Project ",
  "<span>GAM 365</span> Advanced Game Design ",
  "<span>GAM 312</span> Playtesting ",
  "<span>GAM 250</span> Game Sound Design I ",
  "<span>IT 223</span> Data Analysis ",
  "<span>DC 228</span> Ethics in Computer Games and Cinema ",
  "<span>IT 228</span> Ethics in Computer Games and Cinema ",
  "<span>GAM 392</span> Game Modification Workshop ",
  "<span>GAM 394</span> Game Development Project I ",
  "<span>GAM 395</span> Game Development Project II "
];

const prevYears = [year_1920, year_1819, year_1718, year_1617];

prevYears.forEach(year => {
  const extras = year.filter(course =>
    year_2021.every(otherCourse => course.substring(6, course.indexOf("</")) != otherCourse)
  );
});
